### DISCUSSION TITLE
Using an IM72D128 PDM mic with sensor.community (Helmut Bitter) PDM to I2S adapter

### DISCUSSION THREAD

**Discussion by pe0ter** [stas-sl/esphome-sound-level-meter#25] [Show and tell]
I have used your sensor-community-example script to create another ESP32 sound level meter, this time with a IM72D128 PDM microphone connected via a sensor.community (Helmut Bitter) PDM to I2S adapter to compare with my ESP32 and DNMS ICS43434 and DNMS IM72D128 microphones.
To get proper measurement levels at both 94dB and 114dB I had to change the mic_sensitivity_ref: value from 94 to 103.4 to get both levels within 0.15dB. For my ESP32 meter with ICS43434 microphone I had to change this value from 94 to 93.7 to get the same results.
Not sure if this was the right parameter to tweak but calibrater measurement results showed it worked.
#55020 DNMS ICS43434
#86901 DNMS IM72D128
#87587 ESP32 ICS43434
#87662 ESP32 IM72D128

**Comment by stas-sl** [comment]
Cool!

> Not sure if this was the right parameter to tweak but calibrater measurement results showed it worked.

A bit cleaner way to achieve the same result, would be to specify `mic_sensitivity` and `mic_sensitivity_ref` according to the mic datasheet and then apply any additional adjustment by specifying `offset`. 

From IM72D128's datasheet we can see that its sensitivity is -36 dBFS at 94 dBSPL
<img width="726" alt="image" src="https://github.com/stas-sl/esphome-sound-level-meter/assets/4602302/79d7e35d-88ab-4709-8c64-8355b4eec232">

```yaml
# see your mic datasheet to find sensitivity and reference SPL.
# those are used to convert dB FS to db SPL
mic_sensitivity: -36dB
mic_sensitivity_ref: 94dB
# additional offset if needed
offset: -0.6dB
```
