### DISCUSSION TITLE
Baby cry passband filter

### DISCUSSION THREAD

**Discussion by Rvh91** [stas-sl/esphome-sound-level-meter#9] [Ideas]
To me a great application for the microphone would be to detect baby cries. I Noticed that thresholding based purely on A or Z weighting would prove difficult, due to different background level noises. According to literature, the cry of a baby is predominantly located in the 400 to 650Hz range. It would be great if we could easily construct additional weighting filters based on a certain frequency.

Would it be possible to construct a filter with a GUI to automatically obtain the sos filter coefficients?

**Comment by stas-sl** [comment]
TBH I'm not really a DSP expert, I learned a bit while working on this project, but it is complicated topic. 

Nevertheless, it is definitely possible to construct band pass filter that you described. I'm not sure what's your DSP/math/programming background, but you can check out my [notebook](https://github.com/stas-sl/esphome-sound-level-meter/blob/main/math/filter-design.ipynb) (if you've not seen it yet) to learn how to work with filters in python and how to convert them to SOS form. Actually it could be as simple as calling `scipy.signal.butter` with required parameters. But you have to be careful specifying correct parameter values and using obtained coefficients with correct sign. To double check, you might use `sosfreqz` to obtain frequency response of your filter and plot it. Or you can actually record the sound, load it in notebook, plot its spectrogram/psd using matplotlib to see what frequencies are there, then apply filter to it and again plot resulting spectrogram or just listen to it to verify that the filter is working.

Probably there are other tools like MATLAB or online GUI where you can do the same, but I'm just sharing what I'm more familiar with and what was using.

**Reply by Rvh91** [reply]
I'm actually playing around a bit in matlab after finding the [scripts](https://github.com/ikostoski/esp32-i2s-slm/tree/master/math) you linked. I've been able to construct a bandpass filter and represent it in sos form, but for some reason i'm getting 6 coefficients per row rather than the 5 in your code, which I think results in the following error:

`while scanning for the next token
found character '\t' that cannot start any token
  in "/config/esphome/******.yaml", line 162, column 63:
     ... 79 0.000000056758 0.000000028379	1	-1.97016212542888	0.971208059 ...`

**Reply by stas-sl** [reply]
Yes, you can see comments on top of coefficients. I'm using implicit a0=1, so if you have a0 != 1, you can just divide both numerator and denominator by it.
```yaml
# group 1.2 (A-weighting)
- filters:
    # for now only SOS filter type is supported, see math/filter-design.ipynb
    # to learn how to create or convert other filter types to SOS
    - type: sos
      coeffs:
        # A-weighting:
        #       b0           b1            b2             a1            a2
        - [ 0.16999495 ,  0.741029   ,  0.52548885 , -0.11321865 , -0.056549273]
        - [ 1.         , -2.00027    ,  1.0002706  , -0.03433284 , -0.79215795 ]
        - [ 1.         , -0.709303   , -0.29071867 , -1.9822421  ,  0.9822986  ]
```
<img width="910" alt="image" src="https://github.com/stas-sl/esphome-sound-level-meter/assets/4602302/161f582e-75f8-47b4-a3ca-11380a713ef5">
