### ISSUE TITLE
SLM doesn't start automatically on boot when a switch is configured

### ISSUE THREAD

**Issue by olivierbeytrison** [stas-sl/esphome-sound-level-meter#14]
Hello,

First thanks for the nice component. Works very well! I use it as a barking detector when we're not home ;)

I faced a small issue : despite having ``is_on: true`` in the yaml (as defined in the example config on the repo), when the ESP boot the sound level meter is turned off. I have to use the switch in HA to enable it.

While digging in the logs, I saw that the switch has a default restore mode to off. Adding ``restore_mode: ALWAYS_ON `` solved my issue. But his makes the ``is_on: true`` parameter useless (in case the switch is configured). So maybe there's a nicer way to work around this or a small information to add to the the docs/examples.

Hope this helps.
Thanks again for the nice work!
Regards,
Olivier B.

**Comment by olivierbeytrison** [comment]
for reference, below the complete switch template :
```yaml
switch:
  - platform: template
    name: "Sound Level Meter Switch"
    restore_mode: ALWAYS_ON 
    lambda: |-
      return id(sound_level_meter1).is_on();
    turn_on_action:
      then: sound_level_meter.turn_on
    turn_off_action:
      then: sound_level_meter.turn_off
```
