### ISSUE TITLE
SPH0645: values are wrong

### ISSUE THREAD

**Issue by Electronlibre2012** [stas-sl/esphome-sound-level-meter#3]
Hello

i try your component and if i use advanced example code i have 121db and if i speak or clap my hand nothing happend.

I try the minimal sample code and i get 104db and same, not a lot of difference if i speak or clap my hand close to the mic nothing change.

I use a SPH0645 like this :
```
i2s:
  bck_pin: GPIO23
  ws_pin: GPIO18
  din_pin: GPIO19
  sample_rate: 48000            # default: 48000
  bits_per_sample: 32           # default: 32
```

any idea please why i doesnt work?

**Comment by stas-sl** [comment]
I haven't used SPH0645 myself, but most probably it is either wiring or bit depth/channels/format issue. You might need to experiment a bit with different settings. For example trying to connect L/R to GND or +3V.

Have you also used `bits_shift` setting? 

I looked into its spec, it says data precision is 18 bits:
<img width="373" alt="image" src="https://user-images.githubusercontent.com/4602302/226112206-e9d71884-bfa0-473d-be27-f906f6138b8b.png">

So you might try:

```yaml
  bits_per_sample: 32 
  bits_shift: 14  # 32 - 18

# or

  bits_per_sample: 24
  bits_shift: 6 # 24 - 18
```

**Comment by Electronlibre2012** [comment]
thanks for your help,

````
bits_per_sample: 24
bits_shift: 6
````
give "-inf" value but

````
bits_per_sample: 32 
bits_shift: 14  # 32 - 18
````

value are still at 104db but when i clap my hand it goes to 112db max.

I already try to solder SEL to GND,

i try right now to put on 3.3V to see if something change

**Comment by Electronlibre2012** [comment]
````
bits_per_sample: 32 
bits_shift: 14  # 32 - 18
````
with SEL on 3.3v give "-inf" value, "infinite" i guess...

**Comment by Electronlibre2012** [comment]
````
bits_per_sample: 24
bits_shift: 6
````
with SEL on 3.3v give 119 db and not move.

Seems the more accurate is 32/14 with SEL on GND...

I dont understand. Must i try another value?

**Comment by Electronlibre2012** [comment]
[[This shows the compatibility problem between the ESP32 I2S interface and the SPH0645LM4H microphone.](https://hackaday.io/project/162059-street-sense/log/160705-new-i2s-microphone)](url) seems : This shows the compatibility problem between the ESP32 I2S interface and the SPH0645LM4H microphone. LOL

What mic do you use please? a INMP441 I2S ?

**Comment by stas-sl** [comment]
Have your read Ivan's note on SPH0645? https://hackaday.io/project/166867-esp32-i2s-slm

I guess that might be the issue. It needs specific initialisation to be applied to work correctly. And also an additional DC blocker filter, which you can add actually in config, copying coefficients from Ivan's repository. But the main issue is that I don't have that specific initialisation needed.

You might try Ivan's project to see if it outputs correct values. Or you can try forking or copying my component locally and add https://github.com/ikostoski/esp32-i2s-slm/blob/b643efa1beae51b84d4ad9b2bfa35d439c81e9b6/esp32-i2s-slm.ino#LL272C3-L277C9 those lines to i2s component setup.

**Comment by stas-sl** [comment]
Well, you found it yourself )

Yes, I'm using INMP441, but it is also a bit outdated. The best option AFAIK should be ICS 43434, but those are harder to find.

**Comment by stas-sl** [comment]
You can probably add it to config, without modifying the component, thought I haven't tried it:
```yaml
esphome:
  on_boot:
    then:
      - lambda: !lambda |-
          REG_SET_BIT(I2S_TIMING_REG(0), BIT(9));   
          REG_SET_BIT(I2S_CONF_REG(0), I2S_RX_MSB_SHIFT);  
```

**Comment by Electronlibre2012** [comment]
> You might try Ivan's project to see if it outputs correct values. Or you can try forking or copying my component locally and add https://github.com/ikostoski/esp32-i2s-slm/blob/b643efa1beae51b84d4ad9b2bfa35d439c81e9b6/esp32-i2s-slm.ino#LL272C3-L277C9 those lines to i2s component setup.

yes, buts its arduino ide...not esphome...

with your peace of code added, its 98db and doesn change anymore ...sorry, doesnt work...

Thanks

I wait for the  INMP441...in 3 weeks LOL

**Comment by stas-sl** [comment]
Have you applied DC blocking filter?

As reported here https://forums.adafruit.com/viewtopic.php?f=19&p=616024, looks like the signal is shifted down by half of full scale, so when calculating RMS it will be equivalent to pretty loud sound. Instead the signal should oscillate around 0. To achieve this, DC blocking filter should be used. 

Again I can't test it, but I hope those are correct filter coefficients. So the final config should be smth like this:

```yaml
esphome:
  name: sound-level-meter
  on_boot:
    then:
      - lambda: !lambda |-
          REG_SET_BIT(I2S_TIMING_REG(0), BIT(9));   
          REG_SET_BIT(I2S_CONF_REG(0), I2S_RX_MSB_SHIFT);  

external_components:
  - source: github://stas-sl/esphome-sound-level-meter

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:
  level: DEBUG

i2s:
  bck_pin: 23
  ws_pin: 18
  din_pin: 19
  sample_rate: 48000            
  bits_per_sample: 32           
  bits_shift: 14

sound_level_meter:
  update_interval: 1s           
  mic_sensitivity: -26dB     
  mic_sensitivity_ref: 94dB

  groups:
    - filters:
        - type: sos
          coeffs: 
            # DC-blocker
            #        b0                 b1          b2      a1    a2          
            - [1.00123377961525, -1.00123377961525, 0.0, -0.9992, 0.0]
    - sensors:
        - type: eq
          name: Leq_1s
```
