### ISSUE TITLE
Updating to i2s_audio component

### ISSUE THREAD

**Issue by mikenorgate** [stas-sl/esphome-sound-level-meter#5]
Now that ESPHome has an official i2s_audio component https://esphome.io/components/i2s_audio.html do you have any plans to update the sound level meter to use that implementation?

**Comment by stas-sl** [comment]
Yeah, I know, it would make sense of course. But unfortunately it lacks a few features for now that I consider rather important. First one is probably quite easy to fix/implement. Currently sample rate/bits per sample are hardcoded there as 16bits@16kHz. Sound meter will of course work with it, but you might need to recalculate all IIR coefficients and probably loose some precision. I don't know how much the difference will be, but I'd prefer rather more precision than less :) I hope, ability to specify audio quality via config will be implemented in the official i2s_audio component at some point.

https://github.com/esphome/esphome/blob/59d6b3afa09c51dc92f036fb8ee746d84489a3ea/esphome/components/i2s_audio/microphone/i2s_audio_microphone.cpp#L27-L41

```cpp
  i2s_driver_config_t config = {
      .mode = (i2s_mode_t) (I2S_MODE_MASTER | I2S_MODE_RX | I2S_MODE_PDM),
      .sample_rate = 16000,
      .bits_per_sample = I2S_BITS_PER_SAMPLE_16BIT,
      .channel_format = I2S_CHANNEL_FMT_ONLY_RIGHT,
      .communication_format = I2S_COMM_FORMAT_STAND_I2S,
      .intr_alloc_flags = ESP_INTR_FLAG_LEVEL1,
      .dma_buf_count = 4,
      .dma_buf_len = 256,
      .use_apll = false,
      .tx_desc_auto_clear = false,
      .fixed_mclk = 0,
      .mclk_multiple = I2S_MCLK_MULTIPLE_DEFAULT,
      .bits_per_chan = I2S_BITS_PER_CHAN_DEFAULT,
  };
```
Second feature is probably more complicated. Currently I'm reading audio data in a separate FreeRTOS task, which means that it can read/process audio even if there are other long running tasks in parallel (like HTTP/MQTT requests). Depending on your config/setup you might have or have not them, but I do have and I'd like not to loose audio data. 

Considering these 2 issues, I'd say I don't plan to use official i2s_audio for now, but if it will change in future, I can change my mind :)

**Comment by wojciechczyz** [comment]
Hi Stas,

bits_per_sample was added recently. Hopefully, sample rate would come soon too:
https://github.com/esphome/feature-requests/issues/2289

Cheers!

**Comment by karrui** [comment]
For those tracking this, `sample_rate` seems to have been [added](https://esphome.io/components/microphone/i2s_audio#configuration-variables)! 

@stas-sl would this be good enough for i2s_audio support?

**Comment by mafrosis** [comment]
One benefit of using the `i2s_audio` component from upstream will be continued compatibility. As folks enhance esphome to support the newer SOCs (eg. S3, C6), this project will also become compatible

**Comment by tom-parkinson** [comment]
There's a deprecation warning from ESPHome 2025.7.0 (which now uses arduino-esp32 3.1.1) about the i2s library:

`In file included from /.platformio/packages/framework-arduinoespressif32-libs/esp32/include/driver/deprecated/driver/i2s.h:23,
                 from src/esphome/components/i2s/i2s.h:4,
                 from src/esphome.h:38,
                 from src/main.cpp:3:
/.platformio/packages/framework-arduinoespressif32-libs/esp32/include/driver/deprecated/driver/adc.h:19:2: warning: #warning "legacy adc driver is deprecated, please migrate to use esp_adc/adc_oneshot.h and esp_adc/adc_continuous.h for oneshot mode and continuous mode drivers respectively"
      |  ^~~~~~~
/.platformio/packages/framework-arduinoespressif32-libs/esp32/include/driver/deprecated/driver/i2s.h:27:2: warning: #warning "This set of I2S APIs has been deprecated, please include 'driver/i2s_std.h', 'driver/i2s_pdm.h' or 'driver/i2s_tdm.h' instead. if you want to keep using the old APIs and ignore this warning, you can enable 'Suppress legacy driver deprecated warning' option under 'I2S Configuration' menu in Kconfig"`

Perhaps this might be a reason to move over to the official `i2s_audio` component?

**Comment by stas-sl** [comment]
Hi!

If someone's still interested in this component (despite the official [sound_level](https://esphome.io/components/sensor/sound_level.html) component is already available), I've switched to using the official I2S microphone as requested in the issue. This is now available in the [dev branch](https://github.com/stas-sl/esphome-sound-level-meter/tree/dev) for anyone who wants to try it out. I still need to do some testing before merging it into the main branch. 

Additionally, the configuration format for specifying filters has changed. You can find the updated configuration details in the [README](https://github.com/stas-sl/esphome-sound-level-meter/blob/dev/README.md).

```yaml

external_components:
  - source: github://stas-sl/esphome-sound-level-meter@dev

i2s_audio: 
  i2s_lrclk_pin: GPIO18
  i2s_bclk_pin: GPIO23

microphone:
  - platform: i2s_audio
    id: mic
    adc_type: external
    i2s_din_pin: GPIO19
    channel: left
    sample_rate: 48000
    bits_per_sample: 32bit
    i2s_mode: primary

sound_level_meter:
  microphone: 
    microphone: mic
    bits_per_sample: 32

  update_interval: 1s
  mic_sensitivity: -26dB
  mic_sensitivity_ref: 94dB

  dsp_filters:
    - id: f_a                      # A weighting @ 48kHz
      type: sos
      coeffs:
        #       b0           b1            b2             a1            a2
        - [0.16999495,    0.741029,    0.52548885,   -0.11321865, -0.056549273]
        - [1.,           -2.00027,     1.0002706,    -0.03433284, -0.79215795 ]
        - [1.,           -0.709303,   -0.29071867,   -1.9822421,   0.9822986  ]

  sensors:
    - type: eq
      name: LAeq_1s
      id: LAeq_1min
      unit_of_measurement: dBA
      dsp_filters: f_a

# you can also have official sound_level running alongside
sensor:
  - platform: sound_level
    microphone: mic
    passive: true
    rms:
      name: Average Loudness
```
